### ISSUE TITLE
Possibility of using redux dev tools?

### ISSUE THREAD

**Issue by slightlytyler** [loggur/lumbur#2]
Haven't tried integrating them yet but as I dive deeper into a test app I'm quickly realizing how critical they are to my workflow. Would definitely be down to contribute, just wanted to get your opinion first

**Comment by timbur** [comment]
I personally haven't found any need for them when using the providers paradigm, since everything becomes so simple/predictable.  How are they critical to your workflow?  I'm curious.

**Comment by slightlytyler** [comment]
They're a great visual tool for debugging action dispatching and state reduction. Not critical but a great (and immediate) sanity checker. The [issue](https://github.com/loggur/react-redux-provide/issues/10) I mentioned here would have been immediately apparent, instead I had to dig to discover the source. The time travel feature has also occasionally been incredibly useful

**Comment by timbur** [comment]
I see.  I'm glad to integrate anything that would be helpful!

**Comment by timbur** [comment]
Related thread: https://github.com/loggur/react-redux-provide/issues/24
